import { storage } from './storage';
import { generateId } from './uuid';
import { statusMachine } from './status-machine';
import type { Application } from '@/types/application';

export function createIndividualSeedApplication(userId: string): Application {
  const now = new Date().toISOString();
  const applicationId = `seed-individual-${userId}`;

  return {
    id: applicationId,
    userId,
    status: 'draft',
    statusHistory: [statusMachine.createStatusHistory(null, 'draft', userId)],
    createdAt: now,
    updatedAt: now,
    data: {
      applicationId,
      userId,
      applicationType: 'individual',
      applicationTypeLocked: true,
      status: 'draft',
      statusHistory: [statusMachine.createStatusHistory(null, 'draft', userId)],
      createdAt: now,
      updatedAt: now,
      currentStep: '/application/review',
      completedSteps: [
        '/application',
        '/application/contact',
        '/application/education',
        '/application/work-history',
        '/application/financials',
        '/application/clients',
        '/application/conflicts',
        '/application/due-diligence',
        '/application/references',
      ],
      isDirty: false,
      lastSaved: new Date(now),
      contactInfo: {
        legalFirstName: 'John',
        legalMiddleName: 'Robert',
        legalLastName: 'Smith',
        alias: 'Jack Smith',
        aliasType: 'nickname',
        streetAddress: '123 Main Street',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        personalEmail: 'john.smith@example.com',
        personalPhone: '(555) 123-4567',
        preferredContact: 'email',
        currentPractice: 'Corporate Law',
        reasonForDentons: 'Seeking to join a global platform with extensive resources and an international network to better serve my clients and expand my practice in corporate M&A.',
      },
      education: {
        education: [
          {
            id: generateId(),
            type: 'law_school',
            institutionName: 'Harvard Law School',
            degree: 'Juris Doctor (JD)',
            graduationYear: '2010',
          },
          {
            id: generateId(),
            type: 'undergraduate',
            institutionName: 'Yale University',
            degree: 'Bachelor of Arts in Political Science',
            graduationYear: '2007',
          },
        ],
        barAdmissions: [
          {
            id: generateId(),
            stateOrCourt: 'New York State Bar',
            barNumber: 'NY12345678',
            admissionDate: '2010-06-15',
            isActive: true,
            inGoodStanding: true,
          },
          {
            id: generateId(),
            stateOrCourt: 'Connecticut State Bar',
            barNumber: 'CT98765432',
            admissionDate: '2011-03-20',
            isActive: true,
            inGoodStanding: true,
          },
        ],
        professionalOrgs: [
          {
            id: generateId(),
            name: 'American Bar Association',
            role: 'Member - Corporate Law Section',
          },
        ],
      },
      workHistory: {
        currentPosition: {
          firmName: 'Smith & Associates LLP',
          location: 'New York, NY',
          title: 'Partner',
          partnerType: 'equity',
          startDate: '2018-01',
          reasonForMove: 'Looking to expand my practice globally and access Dentons international platform and resources.',
        },
        priorPositions: [
          {
            id: generateId(),
            firmName: 'Wilson Partners',
            location: 'New York, NY',
            title: 'Senior Associate',
            startDate: '2013-06',
            endDate: '2017-12',
            reasonForLeaving: 'Promoted to Partner at current firm',
          },
        ],
        plannedTimeOff: true,
        timeOffDetails: '2 weeks in August for pre-planned family vacation',
        expectedNoticePeriod: '60 days',
        everAskedToLeave: false,
        askedToLeaveDetails: '',
      },
      financials: {
        timekeeper: {
          totalBillableHours: { year2022: 1850, year2023: 1920, year2024: 1980, year2025YTD: 950 },
          hoursOriginatedByYou: { year2022: 1200, year2023: 1350, year2024: 1450, year2025YTD: 680 },
          nonBillableHours: { year2022: 150, year2023: 140, year2024: 130, year2025YTD: 60 },
          standardHourlyRate: { year2022: 650, year2023: 700, year2024: 750, year2025YTD: 775 },
          effectiveBillRate: { year2022: 625, year2023: 675, year2024: 720, year2025YTD: 750 },
        },
        billingsCollections: {
          billings: { year2022: 1200000, year2023: 1350000, year2024: 1450000, year2025YTD: 720000 },
          collections: { year2022: 1150000, year2023: 1300000, year2024: 1400000, year2025YTD: 680000 },
        },
        additionalInfo: {
          fiscalYearType: 'calendar',
          fiscalYearExplanation: '',
          unbilledFeesYearEnd: 85000,
          uncollectedBilledFees: 120000,
          uncollectedExplanation: 'Standard 60-90 day payment cycles for large corporate clients',
          originationCreditMethod: 'Originating partner receives 100% credit',
          canIncreaseRate: true,
          newRateIfYes: 800,
          clientRateRestrictions: false,
          restrictionsDetail: '',
        },
        anticipatedCollections: {
          lowEstimate: 1400000,
          baseEstimate: 1600000,
          highEstimate: 1850000,
          higherThanHistoricalExplanation: 'Expanding client base and increased deal flow in technology sector M&A',
        },
        compensation: {
          compensationExpectations: 650000,
          bonusExpectations: 150000,
          businessDevelopmentBudget: 25000,
          practiceExpenditures: 'Client entertainment, marketing materials, conference attendance',
        },
      },
      portableClients: [
        {
          id: generateId(),
          clientName: 'TechCorp Inc.',
          keyContactName: 'Sarah Johnson',
          keyContactTitle: 'General Counsel',
          keyContactEmail: 'sjohnson@techcorp.com',
          affiliatesSubsidiaries: 'TechCorp Holdings, TechCorp International',
          yearsRepresented: 5,
          portableWithin30Days: true,
          numberOfOpenMatters: 3,
          workDescription: 'Corporate M&A, securities offerings, general corporate counsel services',
          staffingDescription: 'Primarily partner-led with associate support on document review and due diligence',
          billRateForClient: 750,
          matters: [
            {
              id: generateId(),
              matterName: 'Series B Fundraising',
              matterDescription: 'Advising on $50M Series B fundraising round including term sheet negotiation and securities compliance',
              adverseParties: 'None',
              howAdverseInvolved: 'N/A',
            },
          ],
          financialHistory: {
            billings: { year2022: 300000, year2023: 325000, year2024: 350000, year2025YTD: 180000 },
            collections: { year2022: 295000, year2023: 320000, year2024: 345000, year2025YTD: 175000 },
          },
          anticipatedCollections: {
            lowEstimate: 320000,
            baseEstimate: 380000,
            highEstimate: 450000,
          },
        },
      ],
      conflicts: {
        clientsAdverseToDentons: [],
        priorClients: [
          {
            id: generateId(),
            clientName: 'Former Tech Startup Inc.',
            natureOfWork: 'Corporate governance, fundraising, and general corporate matters',
            hadMaterialConfidentialInfo: false,
          },
        ],
        prospectiveClients: [],
        proBonoWork: [
          {
            id: generateId(),
            entityName: 'Legal Aid Society',
            natureOfWork: 'Small business formation and advisory services for underserved communities',
            adverseParties: 'None',
            isWorkCurrent: true,
            isWorkPortable: true,
          },
        ],
      },
      dueDiligence: {
        ownershipInterest: { answer: false, explanation: '' },
        publicOffice: { answer: false, explanation: '' },
        businessRelationship: { answer: false, explanation: '' },
        failedToFileTax: { answer: false, explanation: '' },
        failedToPayTax: { answer: false, explanation: '' },
        taxAudit: { answer: false, explanation: '' },
        liensGarnishmentsJudgments: { answer: false, explanation: '' },
        bankruptcyHistory: { answer: false, explanation: '' },
        disciplinaryProceedings: { answer: false, explanation: '' },
        partyToLitigation: { answer: false, explanation: '' },
        malpracticeClaims: { answer: false, explanation: '' },
        falseStatementFraud: { answer: false, explanation: '' },
        potentialClaims: { answer: false, explanation: '' },
        governmentInvestigations: { answer: false, explanation: '' },
        debarmentFromGovernment: { answer: false, explanation: '' },
        boardMemberPositions: { answer: true, explanation: 'Board member of Tech Industry Association' },
        legallyEligibleToWork: true,
        requireVisaSponsorship: false,
        boardMemberships: [
          {
            id: generateId(),
            organizationName: 'Tech Industry Association',
            serviceStartDate: '2022-01-15',
            serviceEndDate: '',
            organizationType: '501c3',
            continueAtDentons: true,
            legalClaimsPending: false,
            hasDOCoverage: true,
            performedLegalServices: false,
            willPerformAtDentons: false,
            willBeDentonsClient: false,
            receiveCompensation: false,
          },
        ],
      },
      references: {
        reference1: {
          name: 'Robert Williams',
          title: 'Managing Partner',
          company: 'Williams & Partners LLP',
          businessType: 'Law Firm',
          phone: '(555) 456-7890',
          email: 'rwilliams@williamspartners.com',
          mayContactPreOffer: true,
        },
        reference2: {
          name: 'Jennifer Davis',
          title: 'General Counsel',
          company: 'TechCorp Inc.',
          businessType: 'Client',
          phone: '(555) 567-8901',
          email: 'jdavis@techcorp.com',
          mayContactPreOffer: true,
        },
        reference3: {
          name: 'David Martinez',
          title: 'Partner',
          company: 'Martinez Law Group',
          businessType: 'Professional Colleague',
          phone: '(555) 678-9012',
          email: 'dmartinez@martinezlaw.com',
          mayContactPreOffer: false,
        },
        recruiter: {
          representedByRecruiter: false,
          recruiterName: '',
          recruiterFirm: '',
          recruiterPhone: '',
          recruiterEmail: '',
          soleRepresentative: false,
        },
      },
      acknowledgment: {
        certificationAccepted: false,
        signature: '',
        signatureDate: '',
      },
      groupOverview: {
        firmName: '',
        firmStructure: '',
        yearEstablished: null,
        totalPartnersInFirm: 0,
        partnersJoiningDentons: 0,
        totalAssociates: 0,
        associatesJoining: 0,
        totalStaff: 0,
        staffJoining: 0,
        currentOfficeLocations: [],
        primaryPracticeAreas: [],
        reasonForTransition: '',
        integrationTimeline: '',
      },
      additionalPartners: [],
      teamMembers: { associates: [], staff: [] },
      combinedFinancials: {
        combinedLowEstimate: 0,
        combinedBaseEstimate: 0,
        combinedHighEstimate: 0,
        totalAnnualPayroll: 0,
        partnerDrawTotal: 0,
        associateSalariesTotal: 0,
        staffSalariesTotal: 0,
        officeSpaceRequirements: '',
        technologyITNeeds: '',
        otherInfrastructure: '',
      },
    } as any,
  };
}

export function createGroupSeedApplication(userId: string): Application {
  const now = new Date().toISOString();
  const applicationId = `seed-group-${userId}`;

  return {
    id: applicationId,
    userId,
    status: 'draft',
    statusHistory: [statusMachine.createStatusHistory(null, 'draft', userId)],
    createdAt: now,
    updatedAt: now,
    data: {
      applicationId,
      userId,
      applicationType: 'group',
      applicationTypeLocked: true,
      status: 'draft',
      statusHistory: [statusMachine.createStatusHistory(null, 'draft', userId)],
      createdAt: now,
      updatedAt: now,
      currentStep: '/application/review',
      completedSteps: [
        '/application',
        '/application/contact',
        '/application/group-overview',
        '/application/partners',
        '/application/team-members',
        '/application/education',
        '/application/work-history',
        '/application/financials',
        '/application/conflicts',
        '/application/due-diligence',
        '/application/references',
        '/application/combined-financials',
      ],
      isDirty: false,
      lastSaved: new Date(now),
      contactInfo: {
        legalFirstName: 'Maria',
        legalMiddleName: 'Elena',
        legalLastName: 'Rodriguez',
        alias: '',
        aliasType: null,
        streetAddress: '456 Park Avenue',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60601',
        personalEmail: 'maria.rodriguez@example.com',
        personalPhone: '(555) 987-6543',
        preferredContact: 'email',
        currentPractice: 'Employment Law',
        reasonForDentons: 'Our practice group seeks to join Dentons to leverage its international network and provide comprehensive employment law services to multinational clients.',
      },
      education: {
        education: [{
          id: generateId(),
          type: 'law_school',
          institutionName: 'Northwestern Pritzker School of Law',
          degree: 'Juris Doctor (JD)',
          graduationYear: '2008',
        }],
        barAdmissions: [{
          id: generateId(),
          stateOrCourt: 'Illinois State Bar',
          barNumber: 'IL87654321',
          admissionDate: '2008-06-10',
          isActive: true,
          inGoodStanding: true,
        }],
        professionalOrgs: [],
      },
      workHistory: {
        currentPosition: {
          firmName: 'Rodriguez Employment Law Group',
          location: 'Chicago, IL',
          title: 'Managing Partner',
          partnerType: 'equity',
          startDate: '2015-01',
          reasonForMove: 'Seeking global platform to serve multinational clients more effectively',
        },
        priorPositions: [],
        plannedTimeOff: false,
        timeOffDetails: '',
        expectedNoticePeriod: '90 days',
        everAskedToLeave: false,
        askedToLeaveDetails: '',
      },
      financials: {
        timekeeper: {
          totalBillableHours: { year2022: 1750, year2023: 1800, year2024: 1850, year2025YTD: 900 },
          hoursOriginatedByYou: { year2022: 1400, year2023: 1450, year2024: 1500, year2025YTD: 750 },
          nonBillableHours: { year2022: 100, year2023: 100, year2024: 100, year2025YTD: 50 },
          standardHourlyRate: { year2022: 550, year2023: 575, year2024: 600, year2025YTD: 625 },
          effectiveBillRate: { year2022: 525, year2023: 550, year2024: 575, year2025YTD: 600 },
        },
        billingsCollections: {
          billings: { year2022: 950000, year2023: 1050000, year2024: 1100000, year2025YTD: 550000 },
          collections: { year2022: 920000, year2023: 1020000, year2024: 1070000, year2025YTD: 530000 },
        },
        additionalInfo: {
          fiscalYearType: 'calendar',
          fiscalYearExplanation: '',
          unbilledFeesYearEnd: 45000,
          uncollectedBilledFees: 75000,
          uncollectedExplanation: 'Normal collection cycle',
          originationCreditMethod: 'Equal distribution among partners',
          canIncreaseRate: true,
          newRateIfYes: 650,
          clientRateRestrictions: false,
          restrictionsDetail: '',
        },
        anticipatedCollections: {
          lowEstimate: 1100000,
          baseEstimate: 1300000,
          highEstimate: 1500000,
          higherThanHistoricalExplanation: 'Expected growth from multinational clients through Dentons network',
        },
        compensation: {
          compensationExpectations: 550000,
          bonusExpectations: 100000,
          businessDevelopmentBudget: 20000,
          practiceExpenditures: 'Client development, conferences, training',
        },
      },
      portableClients: [],
      conflicts: {
        clientsAdverseToDentons: [],
        priorClients: [],
        prospectiveClients: [],
        proBonoWork: [],
      },
      dueDiligence: {
        ownershipInterest: { answer: false, explanation: '' },
        publicOffice: { answer: false, explanation: '' },
        businessRelationship: { answer: false, explanation: '' },
        failedToFileTax: { answer: false, explanation: '' },
        failedToPayTax: { answer: false, explanation: '' },
        taxAudit: { answer: false, explanation: '' },
        liensGarnishmentsJudgments: { answer: false, explanation: '' },
        bankruptcyHistory: { answer: false, explanation: '' },
        disciplinaryProceedings: { answer: false, explanation: '' },
        partyToLitigation: { answer: false, explanation: '' },
        malpracticeClaims: { answer: false, explanation: '' },
        falseStatementFraud: { answer: false, explanation: '' },
        potentialClaims: { answer: false, explanation: '' },
        governmentInvestigations: { answer: false, explanation: '' },
        debarmentFromGovernment: { answer: false, explanation: '' },
        boardMemberPositions: { answer: false, explanation: '' },
        legallyEligibleToWork: true,
        requireVisaSponsorship: false,
        boardMemberships: [],
      },
      references: {
        reference1: {
          name: 'Thomas Anderson',
          title: 'HR Director',
          company: 'Global Corp',
          businessType: 'Client',
          phone: '(555) 111-2222',
          email: 'tanderson@globalcorp.com',
          mayContactPreOffer: true,
        },
        reference2: {
          name: 'Lisa Brown',
          title: 'Partner',
          company: 'Brown & Associates',
          businessType: 'Professional Reference',
          phone: '(555) 222-3333',
          email: 'lbrown@brownassociates.com',
          mayContactPreOffer: true,
        },
        reference3: {
          name: 'James Wilson',
          title: 'General Counsel',
          company: 'Manufacturing Inc.',
          businessType: 'Client',
          phone: '(555) 333-4444',
          email: 'jwilson@manufacturing.com',
          mayContactPreOffer: true,
        },
        recruiter: {
          representedByRecruiter: false,
          recruiterName: '',
          recruiterFirm: '',
          recruiterPhone: '',
          recruiterEmail: '',
          soleRepresentative: false,
        },
      },
      acknowledgment: {
        certificationAccepted: false,
        signature: '',
        signatureDate: '',
      },
      groupOverview: {
        firmName: 'Rodriguez Employment Law Group',
        firmStructure: 'llp',
        yearEstablished: 2015,
        totalPartnersInFirm: 3,
        partnersJoiningDentons: 3,
        totalAssociates: 4,
        associatesJoining: 3,
        totalStaff: 2,
        staffJoining: 2,
        currentOfficeLocations: ['Illinois', 'Wisconsin'],
        primaryPracticeAreas: ['Employment & Labor Law', 'Employment Litigation', 'Employee Benefits'],
        reasonForTransition: 'We are seeking to join Dentons to access its global network and resources, enabling us to better serve multinational clients with complex cross-border employment matters.',
        integrationTimeline: 'We envision a 3-6 month transition period to fully integrate our systems and client relationships.',
      },
      additionalPartners: [
        {
          id: generateId(),
          name: 'Carlos Rodriguez',
          currentTitle: 'Partner',
          practiceArea: 'Employment Litigation',
          yearsOfExperience: 12,
          barAdmissions: 'Illinois',
          portableBookEstimate: 800000,
          compensationExpectation: 450000,
        },
      ],
      teamMembers: {
        associates: [
          {
            id: generateId(),
            name: 'Michael Johnson',
            title: 'Senior Associate',
            practiceArea: 'Employment Law',
            yearsOfExperience: 6,
            currentCompensation: 180000,
            barAdmissions: 'Illinois',
          },
        ],
        staff: [
          {
            id: generateId(),
            name: 'Patricia Martinez',
            title: 'Paralegal',
            yearsWithFirm: 8,
            currentCompensation: 75000,
            responsibilities: 'Case management, client communications',
          },
        ],
      },
      combinedFinancials: {
        combinedLowEstimate: 2500000,
        combinedBaseEstimate: 2800000,
        combinedHighEstimate: 3200000,
        totalAnnualPayroll: 470000,
        partnerDrawTotal: 1400000,
        associateSalariesTotal: 330000,
        staffSalariesTotal: 140000,
        officeSpaceRequirements: 'Approximately 3,500 square feet including 3 partner offices, 4 associate workstations, 2 staff workspaces, conference room, and reception area.',
        technologyITNeeds: 'Standard legal practice management software, document management system, secure email',
        otherInfrastructure: 'Access to research databases, video conferencing facilities',
      },
    } as any,
  };
}

export function createAdminSampleApplications(): Application[] {
  const samples: Application[] = [];

  const now = Date.now();

  samples.push({
    id: 'admin-sample-1',
    userId: 'sample-user-1',
    status: 'under_review',
    statusHistory: [
      statusMachine.createStatusHistory(null, 'draft', 'sample-user-1'),
      statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-1'),
      statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
    ],
    createdAt: new Date(now - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    data: {
      applicationId: 'admin-sample-1',
      userId: 'sample-user-1',
      applicationType: 'individual',
      applicationTypeLocked: true,
      status: 'under_review',
      statusHistory: [
        statusMachine.createStatusHistory(null, 'draft', 'sample-user-1'),
        statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-1'),
        statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
      ],
      createdAt: new Date(now - 15 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
      currentStep: '/application/work-history',
      completedSteps: ['/application', '/application/contact', '/application/education'],
      isDirty: false,
      lastSaved: new Date(now - 5 * 24 * 60 * 60 * 1000),
      contactInfo: {
        legalFirstName: 'Emily',
        legalMiddleName: 'Ann',
        legalLastName: 'Watson',
        alias: '',
        aliasType: null,
        streetAddress: '789 Oak Avenue',
        city: 'Boston',
        state: 'MA',
        zipCode: '02101',
        personalEmail: 'emily.watson@sample.com',
        personalPhone: '(555) 111-1111',
        preferredContact: 'email',
        currentPractice: 'Intellectual Property Law',
        reasonForDentons: 'Looking to join a leading global firm to expand my patent litigation practice and access international IP resources.',
      },
      education: {
        education: [
          {
            id: generateId(),
            type: 'law_school',
            institutionName: 'Boston University School of Law',
            degree: 'Juris Doctor (JD)',
            graduationYear: '2012',
          },
          {
            id: generateId(),
            type: 'undergraduate',
            institutionName: 'MIT',
            degree: 'Bachelor of Science in Computer Science',
            graduationYear: '2009',
          },
        ],
        barAdmissions: [
          {
            id: generateId(),
            stateOrCourt: 'Massachusetts State Bar',
            barNumber: 'MA11223344',
            admissionDate: '2012-11-15',
            isActive: true,
            inGoodStanding: true,
          },
        ],
        professionalOrgs: [
          {
            id: generateId(),
            name: 'Boston Bar Association',
            role: 'IP Committee Member',
          },
        ],
      },
      workHistory: {
        currentPosition: {
          firmName: 'Watson IP Law',
          location: 'Boston, MA',
          title: 'Partner',
          partnerType: 'equity',
          startDate: '2019-01',
          reasonForMove: 'Seeking larger platform for international patent work',
        },
        priorPositions: [
          {
            id: generateId(),
            firmName: 'Tech Patents LLC',
            location: 'Boston, MA',
            title: 'Associate',
            startDate: '2012-09',
            endDate: '2018-12',
            reasonForLeaving: 'Partnership opportunity',
          },
        ],
        plannedTimeOff: false,
        timeOffDetails: '',
        expectedNoticePeriod: '60 days',
        everAskedToLeave: false,
        askedToLeaveDetails: '',
      },
      financials: {
        timekeeper: {
          totalBillableHours: { year2022: 1750, year2023: 1825, year2024: 1900, year2025YTD: 920 },
          hoursOriginatedByYou: { year2022: 1100, year2023: 1200, year2024: 1300, year2025YTD: 650 },
          nonBillableHours: { year2022: 120, year2023: 110, year2024: 100, year2025YTD: 45 },
          standardHourlyRate: { year2022: 550, year2023: 600, year2024: 650, year2025YTD: 675 },
          effectiveBillRate: { year2022: 525, year2023: 575, year2024: 625, year2025YTD: 650 },
        },
        billingsCollections: {
          billings: { year2022: 950000, year2023: 1050000, year2024: 1190000, year2025YTD: 600000 },
          collections: { year2022: 920000, year2023: 1020000, year2024: 1150000, year2025YTD: 580000 },
        },
        additionalInfo: {
          fiscalYearType: 'calendar',
          fiscalYearExplanation: '',
          unbilledFeesYearEnd: 65000,
          uncollectedBilledFees: 85000,
          uncollectedExplanation: 'Standard payment cycles',
          originationCreditMethod: '100% to originating partner',
          canIncreaseRate: true,
          newRateIfYes: 700,
          clientRateRestrictions: false,
          restrictionsDetail: '',
        },
        anticipatedCollections: {
          lowEstimate: 1200000,
          baseEstimate: 1400000,
          highEstimate: 1600000,
          higherThanHistoricalExplanation: 'Growing patent litigation practice',
        },
        compensation: {
          compensationExpectations: 550000,
          bonusExpectations: 125000,
          businessDevelopmentBudget: 20000,
          practiceExpenditures: 'Client development, conferences',
        },
      },
      portableClients: [],
      conflicts: {
        clientsAdverseToDentons: [],
        priorClients: [],
        prospectiveClients: [],
        proBonoWork: [],
      },
      dueDiligence: {
        ownershipInterest: { answer: false, explanation: '' },
        publicOffice: { answer: false, explanation: '' },
        businessRelationship: { answer: false, explanation: '' },
        failedToFileTax: { answer: false, explanation: '' },
        failedToPayTax: { answer: false, explanation: '' },
        taxAudit: { answer: false, explanation: '' },
        liensGarnishmentsJudgments: { answer: false, explanation: '' },
        bankruptcyHistory: { answer: false, explanation: '' },
        disciplinaryProceedings: { answer: false, explanation: '' },
        partyToLitigation: { answer: false, explanation: '' },
        malpracticeClaims: { answer: false, explanation: '' },
        falseStatementFraud: { answer: false, explanation: '' },
        potentialClaims: { answer: false, explanation: '' },
        governmentInvestigations: { answer: false, explanation: '' },
        debarmentFromGovernment: { answer: false, explanation: '' },
        boardMemberPositions: { answer: false, explanation: '' },
        legallyEligibleToWork: true,
        requireVisaSponsorship: false,
        boardMemberships: [],
      },
      references: {
        reference1: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        reference2: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        reference3: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        recruiter: {
          representedByRecruiter: false,
          recruiterName: '',
          recruiterFirm: '',
          recruiterPhone: '',
          recruiterEmail: '',
          soleRepresentative: false,
        },
      },
      acknowledgment: {
        certificationAccepted: false,
        signature: '',
        signatureDate: '',
      },
      groupOverview: {
        firmName: '',
        firmStructure: '',
        yearEstablished: null,
        totalPartnersInFirm: 0,
        partnersJoiningDentons: 0,
        totalAssociates: 0,
        associatesJoining: 0,
        totalStaff: 0,
        staffJoining: 0,
        currentOfficeLocations: [],
        primaryPracticeAreas: [],
        reasonForTransition: '',
        integrationTimeline: '',
      },
      additionalPartners: [],
      teamMembers: { associates: [], staff: [] },
      combinedFinancials: {
        combinedLowEstimate: 0,
        combinedBaseEstimate: 0,
        combinedHighEstimate: 0,
        totalAnnualPayroll: 0,
        partnerDrawTotal: 0,
        associateSalariesTotal: 0,
        staffSalariesTotal: 0,
        officeSpaceRequirements: '',
        technologyITNeeds: '',
        otherInfrastructure: '',
      },
    } as any,
  });

  samples.push({
    id: 'admin-sample-2',
    userId: 'sample-user-2',
    status: 'additional_info_required',
    statusHistory: [
      statusMachine.createStatusHistory(null, 'draft', 'sample-user-2'),
      statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-2'),
      statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
      statusMachine.createStatusHistory('under_review', 'additional_info_required', 'admin@dentons.com', 'Need additional client conflict information'),
    ],
    createdAt: new Date(now - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    data: {
      applicationId: 'admin-sample-2',
      userId: 'sample-user-2',
      applicationType: 'individual',
      applicationTypeLocked: true,
      status: 'additional_info_required',
      statusHistory: [
        statusMachine.createStatusHistory(null, 'draft', 'sample-user-2'),
        statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-2'),
        statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
        statusMachine.createStatusHistory('under_review', 'additional_info_required', 'admin@dentons.com'),
      ],
      createdAt: new Date(now - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
      currentStep: '/application/review',
      completedSteps: [
        '/application',
        '/application/contact',
        '/application/education',
        '/application/work-history',
        '/application/financials',
        '/application/clients',
        '/application/conflicts',
        '/application/due-diligence',
        '/application/references',
        '/application/review',
      ],
      isDirty: false,
      lastSaved: new Date(now - 2 * 24 * 60 * 60 * 1000),
      contactInfo: {
        legalFirstName: 'James',
        legalMiddleName: 'Michael',
        legalLastName: 'Peterson',
        alias: '',
        aliasType: null,
        streetAddress: '456 Corporate Plaza',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '94102',
        personalEmail: 'james.peterson@sample.com',
        personalPhone: '(555) 222-2222',
        preferredContact: 'phone',
        currentPractice: 'Securities and Capital Markets',
        reasonForDentons: 'Joining Dentons will provide access to a global network of capital markets practices and expand my ability to serve public company clients across multiple jurisdictions.',
      },
      education: {
        education: [
          {
            id: generateId(),
            type: 'law_school',
            institutionName: 'Stanford Law School',
            degree: 'Juris Doctor (JD)',
            graduationYear: '2009',
          },
          {
            id: generateId(),
            type: 'undergraduate',
            institutionName: 'UC Berkeley',
            degree: 'Bachelor of Arts in Economics',
            graduationYear: '2006',
          },
        ],
        barAdmissions: [
          {
            id: generateId(),
            stateOrCourt: 'California State Bar',
            barNumber: 'CA99887766',
            admissionDate: '2009-12-01',
            isActive: true,
            inGoodStanding: true,
          },
          {
            id: generateId(),
            stateOrCourt: 'New York State Bar',
            barNumber: 'NY55667788',
            admissionDate: '2010-06-15',
            isActive: true,
            inGoodStanding: true,
          },
        ],
        professionalOrgs: [
          {
            id: generateId(),
            name: 'American Bar Association - Securities Section',
            role: 'Active Member',
          },
        ],
      },
      workHistory: {
        currentPosition: {
          firmName: 'Peterson Capital Law Group',
          location: 'San Francisco, CA',
          title: 'Managing Partner',
          partnerType: 'equity',
          startDate: '2016-01',
          reasonForMove: 'Access to global capital markets practice and international IPO capabilities',
        },
        priorPositions: [
          {
            id: generateId(),
            firmName: 'Wilson Sonsini Goodrich & Rosati',
            location: 'Palo Alto, CA',
            title: 'Senior Associate',
            startDate: '2009-09',
            endDate: '2015-12',
            reasonForLeaving: 'Partnership opportunity at boutique firm',
          },
        ],
        plannedTimeOff: true,
        timeOffDetails: 'Family vacation planned for July 2025 (2 weeks)',
        expectedNoticePeriod: '90 days',
        everAskedToLeave: false,
        askedToLeaveDetails: '',
      },
      financials: {
        timekeeper: {
          totalBillableHours: { year2022: 1950, year2023: 2050, year2024: 2100, year2025YTD: 1050 },
          hoursOriginatedByYou: { year2022: 1500, year2023: 1600, year2024: 1700, year2025YTD: 850 },
          nonBillableHours: { year2022: 150, year2023: 140, year2024: 130, year2025YTD: 60 },
          standardHourlyRate: { year2022: 700, year2023: 750, year2024: 800, year2025YTD: 825 },
          effectiveBillRate: { year2022: 675, year2023: 725, year2024: 775, year2025YTD: 800 },
        },
        billingsCollections: {
          billings: { year2022: 1400000, year2023: 1550000, year2024: 1700000, year2025YTD: 880000 },
          collections: { year2022: 1350000, year2023: 1500000, year2024: 1650000, year2025YTD: 850000 },
        },
        additionalInfo: {
          fiscalYearType: 'calendar',
          fiscalYearExplanation: '',
          unbilledFeesYearEnd: 95000,
          uncollectedBilledFees: 140000,
          uncollectedExplanation: 'Large public company clients on 90-day payment terms',
          originationCreditMethod: 'Originating partner gets 100% credit',
          canIncreaseRate: true,
          newRateIfYes: 850,
          clientRateRestrictions: true,
          restrictionsDetail: 'Some startup clients have rate caps from early engagement letters',
        },
        anticipatedCollections: {
          lowEstimate: 1700000,
          baseEstimate: 2000000,
          highEstimate: 2300000,
          higherThanHistoricalExplanation: 'Pipeline of IPO work and increased M&A activity in tech sector',
        },
        compensation: {
          compensationExpectations: 750000,
          bonusExpectations: 200000,
          businessDevelopmentBudget: 30000,
          practiceExpenditures: 'Industry conferences, client entertainment, thought leadership',
        },
      },
      portableClients: [
        {
          id: generateId(),
          clientName: 'InnovateTech Inc.',
          keyContactName: 'Susan Chang',
          keyContactTitle: 'CEO',
          keyContactEmail: 'schang@innovatetech.com',
          affiliatesSubsidiaries: 'InnovateTech Europe, InnovateTech Asia',
          yearsRepresented: 7,
          portableWithin30Days: true,
          numberOfOpenMatters: 5,
          workDescription: 'IPO preparation, SEC compliance, corporate governance',
          staffingDescription: 'Partner-led with 2 associates on compliance work',
          billRateForClient: 800,
          matters: [
            {
              id: generateId(),
              matterName: 'IPO Preparation',
              matterDescription: 'Preparing for initial public offering, estimated Q3 2025',
              adverseParties: 'None',
              howAdverseInvolved: 'N/A',
            },
          ],
          financialHistory: {
            billings: { year2022: 450000, year2023: 520000, year2024: 600000, year2025YTD: 310000 },
            collections: { year2022: 440000, year2023: 510000, year2024: 590000, year2025YTD: 300000 },
          },
          anticipatedCollections: {
            lowEstimate: 600000,
            baseEstimate: 750000,
            highEstimate: 900000,
          },
        },
      ],
      conflicts: {
        clientsAdverseToDentons: [],
        priorClients: [
          {
            id: generateId(),
            clientName: 'Legacy Biotech Corp',
            natureOfWork: 'IPO and public company representation 2018-2021',
            hadMaterialConfidentialInfo: true,
          },
        ],
        prospectiveClients: [],
        proBonoWork: [],
      },
      dueDiligence: {
        ownershipInterest: { answer: false, explanation: '' },
        publicOffice: { answer: false, explanation: '' },
        businessRelationship: { answer: false, explanation: '' },
        failedToFileTax: { answer: false, explanation: '' },
        failedToPayTax: { answer: false, explanation: '' },
        taxAudit: { answer: false, explanation: '' },
        liensGarnishmentsJudgments: { answer: false, explanation: '' },
        bankruptcyHistory: { answer: false, explanation: '' },
        disciplinaryProceedings: { answer: false, explanation: '' },
        partyToLitigation: { answer: false, explanation: '' },
        malpracticeClaims: { answer: false, explanation: '' },
        falseStatementFraud: { answer: false, explanation: '' },
        potentialClaims: { answer: false, explanation: '' },
        governmentInvestigations: { answer: false, explanation: '' },
        debarmentFromGovernment: { answer: false, explanation: '' },
        boardMemberPositions: { answer: false, explanation: '' },
        legallyEligibleToWork: true,
        requireVisaSponsorship: false,
        boardMemberships: [],
      },
      references: {
        reference1: {
          name: 'David Chen',
          title: 'CFO',
          company: 'InnovateTech Inc.',
          businessType: 'Client',
          phone: '(555) 123-4567',
          email: 'dchen@innovatetech.com',
          mayContactPreOffer: true,
        },
        reference2: {
          name: 'Margaret Sullivan',
          title: 'Partner',
          company: 'Wilson Sonsini',
          businessType: 'Former Colleague',
          phone: '(555) 234-5678',
          email: 'msullivan@wsgr.com',
          mayContactPreOffer: true,
        },
        reference3: {
          name: 'Robert Kim',
          title: 'General Counsel',
          company: 'TechVentures LLC',
          businessType: 'Client',
          phone: '(555) 345-6789',
          email: 'rkim@techventures.com',
          mayContactPreOffer: false,
        },
        recruiter: {
          representedByRecruiter: false,
          recruiterName: '',
          recruiterFirm: '',
          recruiterPhone: '',
          recruiterEmail: '',
          soleRepresentative: false,
        },
      },
      acknowledgment: {
        certificationAccepted: false,
        signature: '',
        signatureDate: '',
      },
      groupOverview: {
        firmName: '',
        firmStructure: '',
        yearEstablished: null,
        totalPartnersInFirm: 0,
        partnersJoiningDentons: 0,
        totalAssociates: 0,
        associatesJoining: 0,
        totalStaff: 0,
        staffJoining: 0,
        currentOfficeLocations: [],
        primaryPracticeAreas: [],
        reasonForTransition: '',
        integrationTimeline: '',
      },
      additionalPartners: [],
      teamMembers: { associates: [], staff: [] },
      combinedFinancials: {
        combinedLowEstimate: 0,
        combinedBaseEstimate: 0,
        combinedHighEstimate: 0,
        totalAnnualPayroll: 0,
        partnerDrawTotal: 0,
        associateSalariesTotal: 0,
        staffSalariesTotal: 0,
        officeSpaceRequirements: '',
        technologyITNeeds: '',
        otherInfrastructure: '',
      },
    } as any,
  });

  const patriciaApp = createGroupSeedApplication('sample-user-3');
  samples.push({
    ...patriciaApp,
    id: 'admin-sample-3',
    status: 'approved',
    statusHistory: [
      statusMachine.createStatusHistory(null, 'draft', 'sample-user-3'),
      statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-3'),
      statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
      statusMachine.createStatusHistory('under_review', 'approved', 'admin@dentons.com', 'Excellent group practice, approved for integration'),
    ],
    createdAt: new Date(now - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
    data: {
      ...patriciaApp.data,
      applicationId: 'admin-sample-3',
      userId: 'sample-user-3',
      status: 'approved',
      statusHistory: [
        statusMachine.createStatusHistory(null, 'draft', 'sample-user-3'),
        statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-3'),
        statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
        statusMachine.createStatusHistory('under_review', 'approved', 'admin@dentons.com'),
      ],
      createdAt: new Date(now - 45 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
      contactInfo: {
        legalFirstName: 'Patricia',
        legalMiddleName: 'Anne',
        legalLastName: 'Johnson',
        alias: '',
        aliasType: null,
        streetAddress: '100 Legal Plaza',
        city: 'Seattle',
        state: 'WA',
        zipCode: '98101',
        personalEmail: 'patricia.johnson@sample.com',
        personalPhone: '(555) 333-3333',
        preferredContact: 'email',
        currentPractice: 'Healthcare Law',
        reasonForDentons: 'Our healthcare practice group seeks to join Dentons to access its global healthcare network and provide comprehensive services to multinational healthcare clients.',
      },
      groupOverview: {
        firmName: 'Johnson Healthcare Law Group',
        firmStructure: 'Partnership',
        yearEstablished: 2010,
        totalPartnersInFirm: 5,
        partnersJoiningDentons: 3,
        totalAssociates: 8,
        associatesJoining: 6,
        totalStaff: 4,
        staffJoining: 3,
        currentOfficeLocations: ['Seattle, WA'],
        primaryPracticeAreas: ['Healthcare Regulatory', 'Healthcare Transactions', 'Healthcare Litigation'],
        reasonForTransition: 'Seeking global healthcare platform to serve multinational hospital systems and pharmaceutical clients.',
        integrationTimeline: 'Q3 2025',
      },
      lastSaved: new Date(now - 1 * 24 * 60 * 60 * 1000),
    },
  });

  const richardBase = createIndividualSeedApplication('sample-user-4');
  samples.push({
    id: 'admin-sample-4',
    userId: 'sample-user-4',
    status: 'rejected',
    statusHistory: [
      statusMachine.createStatusHistory(null, 'draft', 'sample-user-4'),
      statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-4'),
      statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
      statusMachine.createStatusHistory('under_review', 'rejected', 'admin@dentons.com', 'Insufficient portable business'),
    ],
    createdAt: new Date(now - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString(),
    data: {
      ...richardBase.data,
      applicationId: 'admin-sample-4',
      userId: 'sample-user-4',
      status: 'rejected',
      statusHistory: [
        statusMachine.createStatusHistory(null, 'draft', 'sample-user-4'),
        statusMachine.createStatusHistory('draft', 'submitted', 'sample-user-4'),
        statusMachine.createStatusHistory('submitted', 'under_review', 'admin@dentons.com'),
        statusMachine.createStatusHistory('under_review', 'rejected', 'admin@dentons.com'),
      ],
      createdAt: new Date(now - 60 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString(),
      completedSteps: ['/application', '/application/contact'],
      currentStep: '/application/education',
      contactInfo: {
        legalFirstName: 'Richard',
        legalMiddleName: 'Thomas',
        legalLastName: 'Brown',
        alias: '',
        aliasType: null,
        streetAddress: '222 Commerce Street',
        city: 'Dallas',
        state: 'TX',
        zipCode: '75201',
        personalEmail: 'richard.brown@sample.com',
        personalPhone: '(555) 444-4444',
        preferredContact: 'email',
        currentPractice: 'General Practice',
        reasonForDentons: 'Looking for opportunities at a larger firm.',
      },
      lastSaved: new Date(now - 10 * 24 * 60 * 60 * 1000),
    } as any,
  });

  const susanBase = createIndividualSeedApplication('sample-user-5');
  samples.push({
    id: 'admin-sample-5',
    userId: 'sample-user-5',
    status: 'draft',
    statusHistory: [
      statusMachine.createStatusHistory(null, 'draft', 'sample-user-5'),
    ],
    createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
    data: {
      ...susanBase.data,
      applicationId: 'admin-sample-5',
      userId: 'sample-user-5',
      status: 'draft',
      statusHistory: [
        statusMachine.createStatusHistory(null, 'draft', 'sample-user-5'),
      ],
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
      completedSteps: ['/application', '/application/contact', '/application/education', '/application/work-history'],
      currentStep: '/application/financials',
      contactInfo: {
        legalFirstName: 'Susan',
        legalMiddleName: 'Marie',
        legalLastName: 'Miller',
        alias: '',
        aliasType: null,
        streetAddress: '567 Maple Drive',
        city: 'Austin',
        state: 'TX',
        zipCode: '78701',
        personalEmail: 'susan.miller@sample.com',
        personalPhone: '(555) 555-5555',
        preferredContact: 'email',
        currentPractice: 'Family Law',
        reasonForDentons: 'Interested in joining to expand family law practice and access divorce mediation resources.',
      },
      education: susanBase.data.education,
      workHistory: susanBase.data.workHistory,
      financials: {
        timekeeper: {
          totalBillableHours: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
          hoursOriginatedByYou: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
          nonBillableHours: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
          standardHourlyRate: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
          effectiveBillRate: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
        },
        billingsCollections: {
          billings: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
          collections: { year2022: 0, year2023: 0, year2024: 0, year2025YTD: 0 },
        },
        additionalInfo: {
          fiscalYearType: 'calendar',
          fiscalYearExplanation: '',
          unbilledFeesYearEnd: 0,
          uncollectedBilledFees: 0,
          uncollectedExplanation: '',
          originationCreditMethod: '',
          canIncreaseRate: false,
          newRateIfYes: 0,
          clientRateRestrictions: false,
          restrictionsDetail: '',
        },
        anticipatedCollections: {
          lowEstimate: 0,
          baseEstimate: 0,
          highEstimate: 0,
          higherThanHistoricalExplanation: '',
        },
        compensation: {
          compensationExpectations: 0,
          bonusExpectations: 0,
          businessDevelopmentBudget: 0,
          practiceExpenditures: '',
        },
      },
      portableClients: [],
      conflicts: {
        clientsAdverseToDentons: [],
        priorClients: [],
        prospectiveClients: [],
        proBonoWork: [],
      },
      dueDiligence: {
        ownershipInterest: { answer: null, explanation: '' },
        publicOffice: { answer: null, explanation: '' },
        businessRelationship: { answer: null, explanation: '' },
        failedToFileTax: { answer: null, explanation: '' },
        failedToPayTax: { answer: null, explanation: '' },
        taxAudit: { answer: null, explanation: '' },
        liensGarnishmentsJudgments: { answer: null, explanation: '' },
        bankruptcyHistory: { answer: null, explanation: '' },
        disciplinaryProceedings: { answer: null, explanation: '' },
        partyToLitigation: { answer: null, explanation: '' },
        malpracticeClaims: { answer: null, explanation: '' },
        falseStatementFraud: { answer: null, explanation: '' },
        potentialClaims: { answer: null, explanation: '' },
        governmentInvestigations: { answer: null, explanation: '' },
        debarmentFromGovernment: { answer: null, explanation: '' },
        boardMemberPositions: { answer: null, explanation: '' },
        legallyEligibleToWork: null,
        requireVisaSponsorship: null,
        boardMemberships: [],
      },
      references: {
        reference1: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        reference2: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        reference3: { name: '', title: '', company: '', businessType: '', phone: '', email: '', mayContactPreOffer: false },
        recruiter: {
          representedByRecruiter: false,
          recruiterName: '',
          recruiterFirm: '',
          recruiterPhone: '',
          recruiterEmail: '',
          soleRepresentative: false,
        },
      },
      acknowledgment: {
        certificationAccepted: false,
        signature: '',
        signatureDate: '',
      },
      lastSaved: new Date(now - 6 * 60 * 60 * 1000),
    } as any,
  });

  return samples;
}

export function seedApplications(userId: string, isAdmin: boolean = false): void {
  if (typeof window === 'undefined') return;

  const applications = storage.get('applications') || [];
  
  if (!isAdmin) {
    const individualSeedId = `seed-individual-${userId}`;
    const groupSeedId = `seed-group-${userId}`;

    const hasIndividual = applications.some(app => app.id === individualSeedId);
    if (!hasIndividual) {
      const individualApp = createIndividualSeedApplication(userId);
      applications.push(individualApp);
    }

    const hasGroup = applications.some(app => app.id === groupSeedId);
    if (!hasGroup) {
      const groupApp = createGroupSeedApplication(userId);
      applications.push(groupApp);
    }
  }

  if (isAdmin) {
    const adminSamples = createAdminSampleApplications();
    adminSamples.forEach(sample => {
      const exists = applications.some(app => app.id === sample.id);
      if (!exists) {
        applications.push(sample);
      }
    });
  }

  storage.set('applications', applications);
}

export function ensureSeedApplications(userId: string | null, isAdmin: boolean = false): void {
  if (!userId) return;
  seedApplications(userId, isAdmin);
}
